# Form implementation generated from reading ui file
#
# Created by: Titus
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess

class Main():

    def ReadFile(self):

        fName=QtWidgets.QFileDialog.getOpenFileName(caption="Open File", directory="C:\\")
        
        return str(fName[0])

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 130)
        MainWindow.setMaximumSize(QtCore.QSize(720, 130))
        MainWindow.setMinimumSize(QtCore.QSize(720, 130))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SourceText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.SourceText.setGeometry(QtCore.QRect(122, 11, 551, 22))
        self.SourceText.setObjectName("SourceText")
        self.DestinationText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.DestinationText.setGeometry(QtCore.QRect(122, 41, 551, 22))
        self.DestinationText.setObjectName("DestinationText")
        self.ConvertButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ConvertButton.setGeometry(QtCore.QRect(10, 70, 75, 24))
        self.ConvertButton.setObjectName("ConvertButton")
        self.ResultLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ResultLabel.setGeometry(QtCore.QRect(100, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ResultLabel.setFont(font)
        self.ResultLabel.setObjectName("ResultLabel")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 107, 56))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SourceButton = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        self.SourceButton.setFont(font)
        icon = QtGui.QIcon.fromTheme("accessories-character-map")
        self.SourceButton.setIcon(icon)
        self.SourceButton.setObjectName("SourceButton")
        self.verticalLayout.addWidget(self.SourceButton)
        self.DestinationButton = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        self.DestinationButton.setFont(font)
        icon = QtGui.QIcon.fromTheme("accessories-character-map")
        self.DestinationButton.setIcon(icon)
        self.DestinationButton.setObjectName("DestinationButton")
        self.verticalLayout.addWidget(self.DestinationButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.SourceButton.clicked.connect(self.ReadFile)
        self.DestinationButton.clicked.connect(self.SaveFile)
        self.ConvertButton.clicked.connect(self.ConvertFile)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConvertButton.setText(_translate("MainWindow", "Convert"))
        self.ResultLabel.setText(_translate("MainWindow", "TextLabel"))
        self.SourceButton.setText(_translate("MainWindow", "Source Select"))
        self.DestinationButton.setText(_translate("MainWindow", "Dest. Select"))
    
    def ReadFile(self):
        
        fName=QtWidgets.QFileDialog.getOpenFileName(caption="Open File", directory="*.*")
        newfName=fName[0].replace("/","\\")
        self.SourceText.setText(str(newfName))

    def SaveFile(self):

        fName=QtWidgets.QFileDialog.getSaveFileName(caption="Save File",directory="*.*")
        newfName=fName[0].replace("/","\\")
        self.DestinationText.setText(str(newfName))
    
    def ConvertFile(self):

        try:
            sourceName=self.SourceText.text()
            destinationName=self.DestinationText.text()

            scriptName="pyuic6.exe","-x" ,sourceName + "-o" + destinationName

            a=subprocess.run(args=["pyuic6.exe","-x",sourceName,"-o",destinationName],shell=True,check=True)

            if (a.returncode==0):

                self.ResultLabel.setText("Succesfully Converted")
            else:
                self.ResultLabel.setText("Unsuccesfully Converted")
        
        except:
            
            a=0
            self.ResultLabel.setText("Error")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
